### ISSUE TITLE
the code understanding with padding and the non maximum suppression

### ISSUE THREAD

**Issue by twmht** [XiaXuehai/faceboxes#11]
I found that nms implementation (https://github.com/XiaXuehai/faceboxes/blob/master/encoderl.py#L95) use clamp. 

without clamp, the result is wrong, but I have no idea why you apply clamp here.

second,  you also compute pad (https://github.com/XiaXuehai/faceboxes/blob/master/predict.py#L14), I have no idea why you compute pad here.

any idea?

thanks

**Comment by twmht** [comment]
by the way, to speed up the inference process, I have added nms with cuda implementation,  but I have to add nms after pad, otherwise the result is wrong.

**Comment by XiaXuehai** [comment]
1、`xx1 = x1[order[1:]].clamp(min=x1[i])` is to calculate the IOU of boxes. If you don't clamp it, we can't get inter area.
2、the  aspect ratio of face is 1:1, if the image resized to 1024:1024, the detected face is not correct.
