### ISSUE TITLE
different between caffe version?

### ISSUE THREAD

**Issue by yja1** [XiaXuehai/faceboxes#18]
https://github.com/zeusees/FaceBoxes
want to know why fddb val performance different between your pytorch and zeusees caffe version.
I have compare the model, diff is conv1 pool1 pad. but this small diff affect the performance?
or something diff between generate priorbox or loss layer? have not compare priorbox and loss.

**Comment by XiaXuehai** [comment]
Sorry, I did not try the caffe version. it's  complicated.
maybe some parts are different from the paper like data augmentation or the inference pad.

**Comment by yja1** [comment]
I test your model on widerface val.  easy:0.794
have you test on widerface?and the result same to 0.794?
