### ISSUE TITLE
Trainging

### ISSUE THREAD

**Issue by tensorboy** [XiaXuehai/faceboxes#2]
Do you mind to upload`val.txt` and `train.txt` or how to generate these two files?

**Comment by XiaXuehai** [comment]
The training network is writen in` networks.py`  and `multibox_layer.py`. 
You can train the network by running `trainvisdom.py`.

**Comment by tensorboy** [comment]
And it needs `train_rewrite.txt` and `val_rewrite.txt`, right? :)

**Comment by XiaXuehai** [comment]
You can download the wider face and do data processing with `data/handle.py.` Then you can get the twe files.Maybe you should modify the code slightly.

**Comment by tensorboy** [comment]
I got it, thanks!

**Comment by tensorboy** [comment]
[train_rewrite.txt](https://github.com/XiaXuehai/faceboxes/files/2319512/train_rewrite.txt)
[val_rewrite.txt](https://github.com/XiaXuehai/faceboxes/files/2319513/val_rewrite.txt)

Just uploaded the corresponding WiderFace file at here in case anyone needs it. :)

**Comment by tensorboy** [comment]
Updated it to fix the wrong images of the validation set.

[train_rewrite.txt](https://github.com/XiaXuehai/faceboxes/files/2319839/train_rewrite.txt)
[val_rewrite.txt](https://github.com/XiaXuehai/faceboxes/files/2319840/val_rewrite.txt)
