### ISSUE TITLE
initialization

### ISSUE THREAD

**Issue by foralliance** [XiaXuehai/faceboxes#23]
@XiaXuehai 
　　在训练时，通过
　　　　`net.load_state_dict(torch.load('weight/faceboxes.pt'))`
　　载入了模型，但这个模型应该是1个训练好的模型吧．

　　那么模型（各个网络层）该如何初始化化呢？？在code中，貌似并没有这部分的代码．

**Comment by XiaXuehai** [comment]
yes, you are right. we should init the model by xavier according to the paper

**Comment by XiaXuehai** [comment]
有时间可以重新训练下看看，效果应该比原来好吧

**Comment by foralliance** [comment]
加了初始化，再加上昨天对anchor density的修改，这2点应该会使效果有提升．
不过我还是像paper那样用的SGD，没用Adam．

**Comment by foralliance** [comment]
另外你的代码貌似在处理数据集时，貌似并没有体现出减均值的操作？？

**Comment by XiaXuehai** [comment]
是的。不过加了bn貌似减均值意义不大了。

**Comment by foralliance** [comment]
还有2个疑问：

1.
在**计算损失函数时（multibox_loss.py）**，
计算回归损失时：`loc_loss = F.smooth_l1_loss(pos_loc_preds, pos_loc_targets) * 4`．此时只考虑了正样本
计算分类损失时：`conf_loss = F.cross_entropy(preds, targets, reduction='sum') / num_matched_boxes`．此时也只考虑了正样本

**为什么在计算回归损失时，乘以4？？**

2.
在**encoderl.py**中，在**encode函数**中，
```
        inf_flag = wh.abs() > 10000
        if (inf_flag.sum().item() is not 0):
            print('inf_flag has true', wh, boxes)
            print('org_boxes', boxes_org)
            print('max_iou', max_iou, 'max_iou_index', max_iou_index)
            raise 'inf error'
```
**上述代码的作用，意义是什么？？**

**Comment by XiaXuehai** [comment]
1， 回归是没有负样本的，分类的时候是用到负样本的；* 4是因为smooth_l1_loss默认mean，会计算所有的平均，即除以num_pos * 4，乘4是为了平衡conf_loss，不乘应该也没关系
2，这个是因为之前wider face的label中有宽度为0的，会造成loss爆炸，影响训练

**Comment by foralliance** [comment]
> * 4是因为smooth_l1_loss默认mean，会计算所有的平均，即除以num_pos * 4

 这一句不敢苟同．

对于回归损失smooth_l1_loss
`loc_loss = F.smooth_l1_loss(pos_loc_preds, pos_loc_targets) * 4.`
默认参数确实是mean，会计算平均值，但除以的是**num_pos**，并非**num_pos * 4**吧？？除以什么得根据其输入决定，此时的2个输入`pos_loc_preds`, `pos_loc_targets`通过debug，其都是关于pos的结果啊．

**Comment by XiaXuehai** [comment]
https://pytorch.org/docs/stable/nn.html#torch.nn.SmoothL1Loss
>x and y arbitrary shapes with a total of n elements each the sum operation still operates over all the elements, and divides by n.

**Comment by foralliance** [comment]
了解了．通过debug才发现，是我一直搞错了！！这里确实除以的是num_pos * 4，不是num_pos 
感谢！！

**Comment by foralliance** [comment]
@XiaXuehai 
另外，github主页上的曲线是如何得到的，应该是测试的结果吧？？code中貌似并没有提供测试代码！

**Comment by XiaXuehai** [comment]
用inference跑一遍fddb数据，图是用fddb的代码跑出来的，官网有相关代码。

**Comment by foralliance** [comment]
感谢！

**Comment by laidy3** [comment]
用inference跑一遍fddb数据，图是用fddb的代码跑出来的，官网有相关代码。
@XiaXuehai 
我用你的权重跑了fddb数据，但是ROC曲线差很多 请问可能是什么原因呢？还有你跑的时候y1有+4吗，box需要转成int吗？

**Comment by XiaXuehai** [comment]
代码有变动，一个是加入了参数初始化，一个是修改了[anchor的生成](https://github.com/XiaXuehai/faceboxes/issues/22)。模型是还没有重新训练。加4是为了在图上完整显示概率值，fddb不用加。

**Comment by laidy3** [comment]
@XiaXuehai
我是用原来的代码和权重跑的 不+4的话生成的discROC图是这样
![image](https://user-images.githubusercontent.com/34129742/50871371-4ca0cd00-13f6-11e9-932b-82f3c620bed6.png)
请问可能是什么问题呀？

**Comment by XiaXuehai** [comment]
你生成的输出格式是什么样的？
是否是如下格式

> 2002/08/11/big/img_591
> 1
> 193.64362	58.81806	162.27905	212.69354	0.99998283
> 2002/08/26/big/img_265
> 3
> 61.71539	37.439896	84.2059	116.97165	0.9998871
> 297.73483	60.731354	84.01535	123.37494	0.999634
> 160.99176	103.97423	47.357986	60.993637	0.9991849

**Comment by laidy3** [comment]
@XiaXuehai 
嗯嗯 有一些x坐标还是负的 我试过改成0但生成的图差不多
![image](https://user-images.githubusercontent.com/34129742/50879176-f727e880-1414-11e9-9a0c-b8abaa3b9c4f.png)

**Comment by XiaXuehai** [comment]
[这一行](https://github.com/XiaXuehai/faceboxes/blob/master/encoderl.py#L20)改成：
`density = [[-3,-1,1,3],[-2,2],[0]]`
再试试看？
这一行是不准确的，但是和model匹配

**Comment by laidy3** [comment]
@XiaXuehai 
我用的是旧的代码 这一行本来就是这样 会不会是我用fddb工具评估的方式不对？
你能把你的txt文件发我吗？947884964@qq.com
![image](https://user-images.githubusercontent.com/34129742/50879451-eb88f180-1415-11e9-8062-e3a48d16b7ba.png)
