### ISSUE TITLE
Error when use validatiion data

### ISSUE THREAD

**Issue by tensorboy** [XiaXuehai/faceboxes#3]
The validation data is not used  in your training when I add it back, it shows an error, do you have ideas for that bug:

![faceboxes](https://user-images.githubusercontent.com/17189055/44605911-fcef9b00-a79f-11e8-815f-21f914003bdb.png)

**Comment by tensorboy** [comment]
It is because some images at the validation set didn't have labels:

![screenshot from 2018-08-24 13-51-43](https://user-images.githubusercontent.com/17189055/44607312-e1d35a00-a7a4-11e8-9e30-ebb3302762e2.png)

Remove these images will work.

**Comment by XiaXuehai** [comment]
Very nice of you, thanks!

**Comment by tensorboy** [comment]
You are welcome. :)
