### ISSUE TITLE
Keep respect ratio of the original image

### ISSUE THREAD

**Issue by tensorboy** [XiaXuehai/faceboxes#4]
The respect ratio is kept during the testing:
https://github.com/XiaXuehai/faceboxes/blob/master/predict.py#L13
However, it is not for training:
https://github.com/XiaXuehai/faceboxes/blob/master/dataset.py#L74

Do you think it is necessary to keep the respect ration during training?

**Comment by XiaXuehai** [comment]
when training,I use the function https://github.com/XiaXuehai/faceboxes/blob/7d3a459ad7e98c791ce9ad7b9058329f0663f4e4/dataset.py#L67
to crop the image to square,then resize it to (1024,1024),which will keep the respect ratio.

**Comment by tensorboy** [comment]
I got it, thanks!
