### ISSUE TITLE
Data scale is different between training and testing

### ISSUE THREAD

**Issue by tensorboy** [XiaXuehai/faceboxes#5]
The image feeding into the network is between (0, 255) during testing, you can print the value of it:
https://github.com/XiaXuehai/faceboxes/blob/master/predict.py#L19

However, the image during training is between (0, 1.) because `Totensor function`:
https://github.com/pytorch/vision/blob/master/torchvision/transforms/functional.py#L51
 will divide 255 to the original image for the training dataset:
https://github.com/XiaXuehai/faceboxes/blob/master/dataset.py#L78

**Comment by XiaXuehai** [comment]
When testing, the test image will pass the `ListDataset/__getitem__/totensor`, so it will divide 255 during training and testing.

**Comment by tensorboy** [comment]
Great, thanks!
