### ISSUE TITLE
The speed of test

### ISSUE THREAD

**Issue by JingyuanHu** [XiaXuehai/faceboxes#6]
Thank you for your great work. But I can't get the speed described in paper Faceboxes. Just 20fps in GPU.

**Comment by XiaXuehai** [comment]
![image](https://user-images.githubusercontent.com/11585321/45020901-c26ce480-b062-11e8-9726-6286e7ce10f2.png)

**Comment by JingyuanHu** [comment]
That means you can reproduct this result? But I can just get 20fps in 1080Ti and 1.3fps in CPU. Very slow.

**Comment by XiaXuehai** [comment]
Sorry,I didn't understand what you meant at first. 
No, this rep can't get the speed.Maybe we should optimize it in decode part.
