### ISSUE TITLE
Image Value [0, 255] or [0,1]

### ISSUE THREAD

**Issue by xingmimfl** [XiaXuehai/faceboxes#8]
it seems there is an issue in your predict.py. when training, images are rescaled into [0,1] by transform.ToTensor, but in your predict.py, I don't see any operattions that rescales a image into [0,1]

**Comment by XiaXuehai** [comment]
No, the image will be rescaled into [0, 1] only when the input's type is uint8 in pytorch0.41.

**Comment by XiaXuehai** [comment]
I have rescaled image into [0, 1] and trained it again. The output is same with before.
