### ISSUE TITLE
about the density

### ISSUE THREAD

**Issue by twmht** [XiaXuehai/faceboxes#9]
Hi,

When increasing the density of the anchors (https://github.com/XiaXuehai/faceboxes/blob/master/encoderl.py#L34), 

I don't understand why you divide 8.

```
(cx+dx/8.*s*ar, cy+dy/8.*s*ar, s*ar, s*ar)
```

Why divide by 8?

**Comment by XiaXuehai** [comment]
![image](https://user-images.githubusercontent.com/11585321/46457148-e8151700-c7e3-11e8-993f-6e7cc1d22b0c.png)
See this, the A_scale=8 in the first grid. The `(cx, cy) `is the center of the anchor, and `s*ar` is the width and height of the anchor in range(0,1). (dx/8, dy/8) is the offset to the anchor in range(0,1)

**Comment by twmht** [comment]
@XiaXuehai 

I know that the figure means.

But the paper says the scales are 32, 64 and 128.  I don't know where the scale 8 comes from?

**Comment by XiaXuehai** [comment]
It comes from A_scale=8. The two center point of two anchor is divided into 8 parts
